### ISSUE TITLE
concurrent usage and persistent connection

### ISSUE THREAD

**Issue by tonykung06** [algolia/algoliasearch-client-go#315] opened 2017-03-31 11:42 UTC
Hi all,

I am wondering if it is safe to use a persistent algoliasearch.NewClient throughout my application life, and also use it concurrently for like fetching results. I went through the source code, the httpclient is safe to be used by many goroutines, but I am not sure if other internal structs in this client library is designed with concurrent usage in mind. Any help will be appreciated :)

**Comment by aseure** [comment] 2017-03-31 12:13
Hello @tonykung06.

Indeed, the underlying HTTP client is the one from the standard library and we are not modifying any shared state so the client is safe to use in concurrent environment. However, if you encounter or have encountered any issue, feel free to report it, we'll do our best to investigate and fix it.

**Comment by tonykung06** [comment] 2017-04-03 07:45
Got it, Thanks @aseure , I will close this question

**Comment by tonykung06** [comment] 2017-04-12 03:29
it seems the client instance cannot be concurrently used

`Read at 0x00c4216bf9a8 by goroutine 165:
  net/http.(*Transport).RoundTrip()
      /usr/local/Cellar/go/1.7.3/libexec/src/net/http/transport.go:335 +0x227
  net/http.send()
      /usr/local/Cellar/go/1.7.3/libexec/src/net/http/client.go:256 +0x2fe
  net/http.(*Client).send()
      /usr/local/Cellar/go/1.7.3/libexec/src/net/http/client.go:146 +0x1c7
  net/http.(*Client).doFollowingRedirects()
      /usr/local/Cellar/go/1.7.3/libexec/src/net/http/client.go:528 +0x3ce
  net/http.(*Client).Do()
      /usr/local/Cellar/go/1.7.3/libexec/src/net/http/client.go:187 +0x17d
 app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch.(*Transport).tryRequest()
      /app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch/transport.go:241 +0x19f
 app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch.(*Transport).request()
      /app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch/transport.go:171 +0x132
 app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch.(*client).request()
      /app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch/client.go:190 +0xc2
 app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch.(*index).Search()
      /app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch/index.go:448 +0x410`


`Previous write at 0x00c4216bf9a8 by goroutine 164:
 app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch.defaultTransport()
      /app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch/transport.go:133 +0x5d
 app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch.(*Transport).resetDialTimeout()
      /app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch/transport.go:320 +0x75
 app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch.(*Transport).request()
      /app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch/transport.go:173 +0x1cc
 app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch.(*client).request()
      /app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch/client.go:190 +0xc2
 app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch.(*index).Search()
      /app/vendor/github.com/algolia/algoliasearch-client-go/algoliasearch/index.go:448 +0x410`

**Comment by aseure** [comment] 2017-04-12 07:39
Hi @tonykung06,

This is unfortunate. Could you send me a sample of code so that I can reproduce it locally? Also, I would need the version of the API client you are using. From the trace you sent, I assume you're using Go 1.7.3. Did you experience the issue with later version of Go?

Best regards,

**Comment by aseure** [comment] 2017-06-06 11:59
Hello @tonykung06,

I haven't got any news from you since April. Did you find the root cause of the race condition you have encountered? If not, could you answer the questions from my previous message so that I can better help you.

Best regards,

**Comment by aseure** [comment] 2017-06-26 09:31
Hello @tonykung06,

Since I'm not receiving news from you regarding this issue, I'm closing it.

Of course, feel free to re-open it if you have new informations regarding this case, I'll be happy to help.

**Closed by aseure** 2017-06-26 09:31 UTC
